"use client"

import Image from "next/image"
import Link from "next/link"
import { useSearchParams } from "next/navigation"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ArrowRight, MapPin, Users } from "lucide-react"

export function CommunityPageClient(){const raw=useSearchParams().get("tab")||"chapters"; const active=raw==="field-days"?raw:"chapters"; return <main><section className="px-6 py-20 lg:px-12"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">Community</p><h1 className="mt-4 text-5xl font-semibold tracking-tight sm:text-6xl">Local knowledge is climate infrastructure.</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Our community network makes environmental action welcoming, useful, and rooted in place.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src="/group-hiking-trail-sunrise-mountains-peaceful-desktop.webp" alt="Community members exploring a local landscape" fill className="object-cover"/></div></div></section><section className="bg-secondary/55 py-16"><div className="mx-auto max-w-6xl px-6"><Tabs value={active}><TabsList className="grid h-auto grid-cols-2"><TabsTrigger value="chapters" asChild><Link href="/community?tab=chapters">Local chapters</Link></TabsTrigger><TabsTrigger value="field-days" asChild><Link href="/community?tab=field-days">Field days</Link></TabsTrigger></TabsList><TabsContent value="chapters" className="pt-10"><div className="rounded-3xl bg-card p-8 lg:p-12"><Users className="h-8 w-8 text-primary"/><h2 className="mt-5 text-3xl font-semibold">Small teams. Shared tools. Lasting capacity.</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-muted-foreground">Chapters identify local priorities, host learning events, lead community-science projects, and help care for nearby restoration sites. UPVED supplies training, microgrants, safety guidance, and measurement support.</p><Link href="/join?tab=volunteer" className="mt-8 inline-flex items-center gap-2 font-semibold text-primary">Start or join a chapter <ArrowRight className="h-4 w-4"/></Link></div></TabsContent><TabsContent value="field-days" className="pt-10"><div className="rounded-3xl bg-card p-8 lg:p-12"><MapPin className="h-8 w-8 text-primary"/><h2 className="mt-5 text-3xl font-semibold">Learn the landscape by working in it.</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-muted-foreground">Open field days combine useful work with practical learning: native planting, creek cleanup, biodiversity surveys, tree care, and heat mapping. No prior experience is required.</p><Link href="/events" className="mt-8 inline-flex items-center gap-2 font-semibold text-primary">Find a field day <ArrowRight className="h-4 w-4"/></Link></div></TabsContent></Tabs></div></section></main>}
