"use client"

import Image from "next/image"
import Link from "next/link"
import { useSearchParams } from "next/navigation"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ArrowRight, BookOpen, Droplets, Sprout, Users } from "lucide-react"

const programs = {
  restore: { title: "Restore living landscapes", eyebrow: "Habitat restoration", description: "We restore native plant communities, reconnect habitat corridors, and build multi-year stewardship into every site.", image: "/environment-restoration.jpg", alt: "A seedling planted during habitat restoration", icon: Sprout, outcomes: ["Native habitat design and planting", "Three-year establishment care", "Seasonal biodiversity monitoring", "Paid partnerships with local crews"] },
  learn: { title: "Turn climate knowledge into agency", eyebrow: "Environmental education", description: "Hands-on learning helps students and residents understand their local environment and act with confidence.", image: "/environment-research.jpg", alt: "A healthy forest used for field research", icon: BookOpen, outcomes: ["School-ready field modules", "Teacher and youth-leader training", "Open community workshops", "Project-based climate learning"] },
  mobilize: { title: "Make local action easier", eyebrow: "Community mobilization", description: "We equip neighborhood teams with small grants, practical tools, expert guidance, and a clear path from idea to impact.", image: "/group-walking-nature-wellness-minimal-desktop.webp", alt: "Local environmental volunteers walking together", icon: Users, outcomes: ["Chapter launch support", "Community science training", "Tools and microgrants", "Shared impact measurement"] },
}

export function GatheringsPageClient() {
  const requested = useSearchParams().get("tab") || "restore"
  const active = requested in programs ? requested : "restore"
  return <main><section className="bg-[#173f32] px-6 py-20 text-white lg:px-12"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#c8e18f]">Our programs</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-tight sm:text-6xl">Practical work for healthy places and prepared communities.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">We fund, build, and evaluate programs that improve ecological health while growing local capacity to care for it.</p></div></section><section className="mx-auto max-w-7xl px-6 py-16 lg:px-12"><Tabs value={active}><TabsList className="grid h-auto w-full grid-cols-3 rounded-2xl bg-muted p-1"><TabsTrigger value="restore" asChild><Link href="/gatherings?tab=restore">Restore</Link></TabsTrigger><TabsTrigger value="learn" asChild><Link href="/gatherings?tab=learn">Learn</Link></TabsTrigger><TabsTrigger value="mobilize" asChild><Link href="/gatherings?tab=mobilize">Mobilize</Link></TabsTrigger></TabsList>{Object.entries(programs).map(([key,p]) => { const Icon=p.icon; return <TabsContent key={key} value={key} className="pt-10"><div className="grid overflow-hidden rounded-3xl border bg-card lg:grid-cols-2"><div className="relative min-h-[380px]"><Image src={p.image} alt={p.alt} fill className="object-cover" /></div><div className="p-8 lg:p-14"><Icon className="h-8 w-8 text-primary"/><p className="mt-6 text-sm font-semibold uppercase tracking-[.18em] text-primary">{p.eyebrow}</p><h2 className="mt-3 text-4xl font-semibold">{p.title}</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">{p.description}</p><h3 className="mt-8 font-semibold">What the program includes</h3><ul className="mt-4 grid gap-3 text-muted-foreground">{p.outcomes.map(x=><li key={x} className="flex gap-3"><Droplets className="mt-1 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul><Link href="/join" className="mt-9 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground">Get involved <ArrowRight className="h-4 w-4"/></Link></div></div></TabsContent>})}</Tabs></section></main>
}
